name: deep_research
channels:
  - defaults
dependencies:
  - python=3.11
  - pip:
      - torch==2.9.0
      - transformers==4.57.1
      - ollama-python==0.1.2
      - ddgs==9.4.0
      - langchain-openai==0.3.27
      - langchain-community==0.3.27
      - openai==1.86.0
      - langchain==0.3.26
      - jupyter==1.1.1
      - ipykernel==6.29.5